# Common base configuration that all services inherit
x-basics: &basics
  env_file:
    - .env
  restart: unless-stopped

services:
  kiwi:
    <<: *basics
    container_name: kiwi
    depends_on:
      - maria-db
    restart: always
    image: pub.kiwitcms.eu/kiwitcms/kiwi:${KIWI_VERSION:-latest}
    ports:
      - ${KIWI_PORT:-1022}:8443
    networks:
      core:
        ipv4_address: 172.20.0.22
      internal:
    volumes:
      - ./volumes/kiwi/uploads:/Kiwi/uploads:Z

    environment:
      # Database configuration
      KIWI_DB_HOST: maria-db
      KIWI_DB_PORT: 3306
      KIWI_DB_NAME: ${KIWI_DB_NAME:-kiwi}
      KIWI_DB_USER: ${KIWI_DB_USER:-kiwi}
      KIWI_DB_PASSWORD: ${KIWI_PASSWORD}
      # Security settings
      SECRET_KEY: ${SECRET_KEY:-"a-random-string-for-development"}

    cap_drop:
      - ALL
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kiwi.rule=Host(`${KIWI_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.kiwi.entrypoints=websecure"
      - "traefik.http.routers.kiwi.tls.certresolver=cloudflare"
      # Point to the HTTPS port instead of HTTP
      - "traefik.http.services.kiwi.loadbalancer.server.port=8443"
      # Tell Traefik to trust the self-signed certificate
      - "traefik.http.services.kiwi.loadbalancer.server.scheme=https"
      - "traefik.http.services.kiwi.loadbalancer.server.tls.insecure=true"
      - "traefik.http.routers.kiwi.middlewares=kiwi-auth,cloudflare-ipallowlist@file"
      - "traefik.http.middlewares.kiwi-auth.basicauth.users=${KIWI_AUTH}"
