services:
  kiwi:
    container_name: kiwi
    depends_on:
      - maria-db
    restart: always
    image: pub.kiwitcms.eu/kiwitcms/kiwi:${KIWI_VERSION:-latest}
    ports:
      - ${KIWI_PORT:-1022}:8080
      - ${KIWI_SSL_PORT:-8443}:8443
    networks:
      core:
        ipv4_address: 172.20.0.22
      internal:

    volumes:
      - ~/volumes/kiwi/uploads:/Kiwi/uploads:Z
    environment:
      KIWI_DB_HOST: maria-db
      KIWI_DB_PORT: ${KIWI_DB_PORT:-nitrate}
      KIWI_DB_NAME: ${KIWI_DB_NAME:-nitrate}
      KIWI_DB_USER: ${KIWI_DB_USER:-nitrate}
      KIWI_DB_PASSWORD: ${KIWI_PASSWORD:-nitrate}
    cap_drop:
      - ALL
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kiwi.rule=Host(`${KIWI_SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.kiwi.entrypoints=websecure"
      - "traefik.http.routers.kiwi.middlewares=cloudflare-ipallowlist@file"
      - "traefik.http.routers.kiwi.tls.certresolver=cloudflare"
      - "traefik.http.services.kiwi.loadbalancer.server.port=8080"
      - "traefik.http.routers.kiwi.middlewares=${KIWI_AUTH:+kiwi-auth}"
      - "traefik.http.middlewares.kiwi-auth.basicauth.users=${KIWI_AUTH}"
